require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'gemfiles/**/*'

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - '*.gemspec'

Metrics/ClassLength:
  Max: 150

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 20

Metrics/ModuleLength:
  Max: 200

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false

Style/DocumentationMethod:
  Enabled: true

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - and
    - but

RSpec/MultipleExpectations:
  Max: 5

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/NestedGroups:
  Max: 10
