---
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.6
  - 2.7
before_install: gem install bundler -v 2.1.4
gemfile:
  - gemfiles/mail_2.7.gemfile
  - gemfiles/mail_2.7.0.gemfile
  - gemfiles/mail_2.6.gemfile
